/**
 * Auto-detect local network IP and update environment
 * This runs before the app starts to ensure correct server URL
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  
  // Priority order: WiFi, Ethernet, then others
  const priorityNames = ['Wi-Fi', 'WiFi', 'WLAN', 'Ethernet', 'eth0', 'en0'];
  
  // First try priority interfaces
  for (const name of priorityNames) {
    if (interfaces[name]) {
      for (const iface of interfaces[name]) {
        if (iface.family === 'IPv4' && !iface.internal) {
          return iface.address;
        }
      }
    }
  }
  
  // Fallback: find any non-internal IPv4 address
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  
  return 'localhost';
}

function updateEnvFile() {
  const ip = getLocalIP();
  const envPath = path.join(__dirname, '.env');
  const serverUrl = ip === 'localhost' ? 'http://localhost:3001' : `http://${ip}:3001`;
  
  console.log(`🔍 Detected local IP: ${ip}`);
  console.log(`🌐 Server URL: ${serverUrl}`);
  
  const envContent = `# Auto-generated by detect-ip.js
# Last updated: ${new Date().toLocaleString()}
VITE_SERVER_URL=${serverUrl}
`;
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log(`✅ Updated .env file with server URL`);
    return { ip, serverUrl };
  } catch (error) {
    console.error(`❌ Failed to write .env file:`, error.message);
    return { ip, serverUrl, error };
  }
}

function updateCSP() {
  const ip = getLocalIP();
  const htmlPath = path.join(__dirname, 'src', 'renderer', 'index.html');
  
  try {
    let html = fs.readFileSync(htmlPath, 'utf8');
    
    // Build CSP with current IP
    const cspParts = [
      `default-src 'self' http://localhost:* http://127.0.0.1:* http://${ip}:* https://accounts.spotify.com https://api.spotify.com https://sdk.scdn.co`,
      `script-src 'self' 'unsafe-inline' https://sdk.scdn.co`,
      `style-src 'self' 'unsafe-inline'`,
      `img-src 'self' data: https: http:`,
      `connect-src 'self' http://localhost:* http://127.0.0.1:* http://${ip}:* ws://localhost:* ws://127.0.0.1:* ws://${ip}:* https://api.spotify.com https://accounts.spotify.com`,
      `font-src 'self' data:`
    ];
    
    const newCSP = cspParts.join('; ') + ';';
    
    // Replace CSP content
    const cspRegex = /(<meta http-equiv="Content-Security-Policy" content=")[^"]*(")/;
    html = html.replace(cspRegex, `$1${newCSP}$2`);
    
    fs.writeFileSync(htmlPath, html);
    console.log(`✅ Updated CSP with IP: ${ip}`);
  } catch (error) {
    console.error(`⚠️  Could not update CSP:`, error.message);
  }
}

// Run the update
const result = updateEnvFile();
updateCSP();

// Export for use in other scripts
module.exports = { getLocalIP, updateEnvFile, updateCSP };
